### ISSUE TITLE
Block Entity alignment is off

### ISSUE THREAD

**Issue by SamAurel** [laymanuel/GravityControl#3] opened 2022-07-24 09:07 UTC
We have the plugin on our server to circumvent the paper dupe fix. After testing with RaysWorks style dupers we noticed that the alignment of the falling block entitys is off by exactly 8 pixels (half a block) in the west direction if they fly towards south end side, or towards north when the blocks fly towards west. I couldnt verify if they universally are misaligned towards northwest, but the alignment 90 deg off axis could be easily seen.
This issue is mainly problematic for collection and processing ( in my case a duping based concrete farm [design by squishy skittlzz]).

**Comment by e-im** [comment] 2022-07-24 09:19
This has been caused not by a bug in GravityControl but a change in CraftBukkit (which Paper is based on). This change here appears to be the cause at a glance: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/991aeda1218e72e9237942071e7ea55cc77b541c

This change is ill-conceived as vec3i does not have that precision so the offset is completely useless. Although I'm not sure what the vanilla behaviour is here.

I noticed this a few days ago and thought it might cause issues here, but I haven't had a chance to take a better look. In the worst case a workaround will be implemented here, although I'd like to get this fixed in paper/craftbukkit if it makes sense.

**Comment by e-im** [comment] 2022-07-25 19:30
This has been fixed in Paper as of build 81. Update Paper to fix the issue. Thanks for the report.

Reference PaperMC/Paper#8182 - https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ef094640942637ee78314416474425a1a53b2a64

**Closed as completed by e-im** 2022-07-25 19:30 UTC
